{
  "openapi": "3.0.0",
  "info": {
    "title": "入廠證件辨識服務API 文件 - OCR Recognition",
    "description": "\n\n## 此服務提供多種文件類型的光學字元辨識 (OCR) 功能。\n\n### **API 文件列表：**\n* 中華民國身分證\n* 全民健康保險卡\n* 中華民國居留證\n* 外勞護照 (越南)\n* 汽車行照\n* 柴油車排煙檢測表\n* 自主管理標章\n* 勞工職業災害保險及保護法第10條規定 (特別加保)\n* 勞保局E化加保申報表 (單筆)\n* 勞保被保險人投保資料表 (勞保局列印)\n* 勞保個人加保完成線上列印\n* 勞保團體加保完成線上列印  \n\n### **使用方式範例:**\n```bash\ncurl -X POST \"https://{SERVER_HOST}/ocr/identity/id_card\"  \n     -H \"accept: application/json\"\n     -H 'Authorization: Bearer {API_KEY}'   \n     -H \"Content-Type: multipart/form-data\"   \n     -F \"file=@/path/to/your/id_card.jpg\"  \n```\n#### 參數說明:\n* -X POST: 指定 HTTP 方法為 POST。  \n* \"https://{SERVER_HOST}/ocr/identity/id_card\": 依照文件類別，選定 API 端點路徑。請將 {SERVER_HOST} 替換為伺服器 IP 或網域名稱（例如 172.24.9.142 或 api.example.com）。  \n* -H \"accept: application/json\": 指定接受的回應格式為 JSON。\n* -H \"Authorization: Bearer {API_KEY}\": 指定授權標頭，請輸入 API 金鑰進行身份驗證。\n* -H \"Content-Type: multipart/form-data\": 指定請求內容類型為 multipart/form-data。  \n* -F \"file=@/path/to/your/id_card.jpg\": 指定要上傳的影像檔案路徑。請將 /path/to/your/id_card.jpg 替換成您實際的檔案路徑。  \n\n\n### **回應代號:**\n* **200 OK:** 成功\n    ```json\n    {\n        \"status\": \"success\",\n        \"data\": {\n        \"姓名\": \"王小明\",\n        \"出生年月日\": \"民國81年10月21日\",\n        \"統一編號\": \"A123456789\"\n        }\n    }\n    ```\n* **400 Bad Request:** 檔案類型無效\n* **422 Unprocessable Entity:** 驗證錯誤\n* **500 Internal Server Error:** 伺服器內部錯誤\n    ",
    "version": "1.0.3"
  },
  "servers": [
    {
      "url": "http://localhost:8088",
      "description": "API Server"
    },
    {
      "url": "https://172.24.9.142",
      "description": "API Server with SSL"
    },
    {
      "url": "http://10.3.156.56:8088",
      "description": "Demo Server"
    },
    {
      "url": "http://10.3.156.56:8080",
      "description": "Demo Server"
    },
    {
      "url": "http://10.3.156.56:2025",
      "description": "Demo Server"
    },
    {
      "url": "http://localhost:2025",
      "description": "Local Development"
    },
    {
      "url": "http://localhost:2024",
      "description": "Local Development"
    }
  ],
  "paths": {
    "/ocr/identity/id_card": {
      "post": {
        "tags": [
          "證件"
        ],
        "summary": "中華民國國民身分證解析",
        "description": "Process an ID card image and extract structured information.",
        "operationId": "id_card",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_id_card"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Id Card"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "姓名": "王小慶",
                    "出生年月日": "民國81年10月21日",
                    "統一編號": "A123456789"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/identity/health_insurance": {
      "post": {
        "tags": [
          "證件"
        ],
        "summary": "全民健康保險卡",
        "description": "Process a health insurance card image and extract structured information.",
        "operationId": "health_insurance",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_health_insurance"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Health Insurance"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "姓名": "王小慶",
                    "身分證號": "A123456789",
                    "出生日期": "81/10/21"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/identity/resident_certificate": {
      "post": {
        "tags": [
          "證件"
        ],
        "summary": "中華民國居留證",
        "description": "Process a resident certificate image and extract structured information.",
        "operationId": "resident_certificate",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_resident_certificate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Resident Certificate"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "姓名": "王小慶",
                    "Name": "Wang Hsiao-Ming",
                    "統一證號": "A123456789",
                    "國籍": "越南",
                    "護照號碼": "A123456789",
                    "出生日期": "1992/10/21",
                    "居留期限": "2030/01/01",
                    "居留事由": "移工-101工程行",
                    "居留地址": "台北市信義區台北101",
                    "核發單位": "台北市服務站",
                    "核發日期": "2024/01/01 換領"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/identity/passport_Vietnam": {
      "post": {
        "tags": [
          "證件"
        ],
        "summary": "外勞護照(越南)",
        "description": "Process a Vietnamese passport image and extract structured information.",
        "operationId": "passport_vietnam",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_passport_vietnam"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Passport Vietnam"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "護照號碼": "A123456789",
                    "姓名": "Nguyen Van A",
                    "身分證號": "123456789",
                    "出生日期": "10/21/1992",
                    "國籍": "VIETNAMESE",
                    "發證日期": "01/01/2020",
                    "到期日期": "01/01/2030",
                    "機讀碼": "\u003C機讀碼內容\u003E"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/vehicle/car_license": {
      "post": {
        "tags": [
          "車輛"
        ],
        "summary": "汽車行照",
        "description": "Process a car license image and extract structured information.",
        "operationId": "car_license",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_car_license"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Car License"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "牌照號碼": "ABC-1234",
                    "牌照類別": "自用小貨車",
                    "燃料種類": "汽油",
                    "車主": "101有限公司",
                    "地址": "台北市信義區信義路五段7號",
                    "廠牌": "Toyota",
                    "出廠年月": "2024.01",
                    "型式": "ABC1234",
                    "排氣量": "2000"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/vehicle/diesel_emission_report": {
      "post": {
        "tags": [
          "車輛"
        ],
        "summary": "柴油車排煙檢測表",
        "description": "Process a diesel emission report image and extract structured information.",
        "operationId": "diesel_emission_report",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_diesel_emission_report"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Diesel Emission Report"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "車主": "101有限公司",
                    "車牌號碼": "ABC-1234",
                    "測試日期及時間": "2024/01/01 10:00:00",
                    "收件及報告發行日期": "2024/01/02",
                    "檢驗種類": "自主管理",
                    "總評": "合格"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/vehicle/self_management_label": {
      "post": {
        "tags": [
          "車輛"
        ],
        "summary": "自主管理標章",
        "description": "Process a self management label image and extract structured information.",
        "operationId": "self_management_label",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_self_management_label"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Self Management Label"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "車號": "ABC-1234",
                    "有效期限": "112年12月31日"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/insurance/article10_special_insurance": {
      "post": {
        "tags": [
          "保險"
        ],
        "summary": "勞工職業災害保險及保護法第10條規定(特別加保)",
        "description": "Process an Article 10 special insurance image and extract structured information.",
        "operationId": "article10_special_insurance",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_article10_special_insurance"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Article10 Special Insurance"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "申報者身分": "自然人雇主",
                    "保險期間": "113/11/11~114/05/10",
                    "table_details": [
                      {
                        "序號": "1",
                        "姓名": "王〇明",
                        "身分證統一編號": "A123456789",
                        "出生日期": "051/**/20",
                        "投保薪資": "30,000",
                        "保險費": "321"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/insurance/e_insurance": {
      "post": {
        "tags": [
          "保險"
        ],
        "summary": "勞保局E化加保申報表(單筆)",
        "description": "Process a e-insurance image and extract structured information.",
        "operationId": "e_insurance",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_e_insurance"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response E Insurance"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "保險證號": "A123456789",
                    "勞退提繳單位編號": "12345678",
                    "單位名稱": "101公司",
                    "姓名": "王小慶",
                    "身分字號": "A123456789",
                    "出生日期": "081/10/21",
                    "身分證號": "A123456789",
                    "申報時間": "113/02/06 12:34:56",
                    "列印時間": "113/02/17 01:23:45"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/insurance/insured_person": {
      "post": {
        "tags": [
          "保險"
        ],
        "summary": "勞保被保險人投保資料表(勞保局列印)",
        "description": "Process an insured person image and extract structured information.",
        "operationId": "insured_person",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_insured_person"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Insured Person"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "姓名": "王小慶",
                    "身分證號": "A123456789",
                    "日期": "113年01月01日",
                    "出生日期": "0810101",
                    "保險證號": "A123456789企業社",
                    "年資計算_迄": "113年02月01日"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/insurance/individual_insurance_online": {
      "post": {
        "tags": [
          "保險"
        ],
        "summary": "勞保個人加保完成線上列印",
        "description": "Process an individual insurance online image and extract structured information.",
        "operationId": "individual_insurance_online",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_individual_insurance_online"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Individual Insurance Online"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "姓名": "王小慶",
                    "身分證號": "A123456789",
                    "網頁下載時間": "113年01月01日 10時10分10秒",
                    "table_details": [
                      {
                        "序號": "1",
                        "異動別": "加保",
                        "生效日期": "112/01/01"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/ocr/insurance/group_insurance_online": {
      "post": {
        "tags": [
          "保險"
        ],
        "summary": "勞保團體加保完成線上列印",
        "description": "Process a group insurance online image and extract structured information.",
        "operationId": "group_insurance_online",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Body_group_insurance_online"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Response Group Insurance Online"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "列印日期": "民國113年11月01日 16時11分28秒",
                    "保險證號": "01234567F",
                    "table_details": [
                      {
                        "序號": "1",
                        "姓名": "王小慶",
                        "身分證號": "A123456789",
                        "出生日期": "0810101",
                        "最近異動別": "薪調",
                        "最近異動日期": "1130101"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/": {
      "get": {
        "summary": "Root",
        "operationId": "root__get",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {

                },
                "example": {
                  "status": "success",
                  "data": "Welcome to OCR Recognition Service"
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "summary": "Health Check",
        "operationId": "health_check_health_get",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {

                },
                "example": {
                  "status": "success",
                  "data": "healthy"
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          }
        }
      }
    },
    "/token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Get OAuth2 token",
        "description": "Authenticate using client secret to get an access token.",
        "operationId": "getToken",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/Body_getToken"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "additionalProperties": true,
                  "type": "object",
                  "title": "Response Gettoken"
                }
              }
            }
          },
          "400": {
            "description": "Invalid file type",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Invalid file type. Only PNG, JPG, and JPEG are allowed."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "example": {
                  "status": "error",
                  "message": "Error message"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Body_article10_special_insurance": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Article 10 special insurance image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_article10_special_insurance"
      },
      "Body_car_license": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Car license image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_car_license"
      },
      "Body_diesel_emission_report": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Diesel emission report image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_diesel_emission_report"
      },
      "Body_e_insurance": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "e-insurance image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_e_insurance"
      },
      "Body_getToken": {
        "properties": {
          "grant_type": {
            "type": "string",
            "title": "Grant Type"
          },
          "username": {
            "type": "string",
            "title": "Username"
          },
          "password": {
            "type": "string",
            "title": "Password"
          },
          "scope": {
            "type": "string",
            "title": "Scope",
            "default": ""
          },
          "client_id": {
            "type": "string",
            "title": "Client Id"
          },
          "client_secret": {
            "type": "string",
            "title": "Client Secret"
          }
        },
        "type": "object",
        "title": "Body_getToken"
      },
      "Body_group_insurance_online": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Group insurance online image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_group_insurance_online"
      },
      "Body_health_insurance": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Health insurance card image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_health_insurance"
      },
      "Body_id_card": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "ID card image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_id_card"
      },
      "Body_individual_insurance_online": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Individual insurance online image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_individual_insurance_online"
      },
      "Body_insured_person": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Insured person image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_insured_person"
      },
      "Body_passport_vietnam": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Vietnamese passport image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_passport_vietnam"
      },
      "Body_resident_certificate": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Resident certificate image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_resident_certificate"
      },
      "Body_self_management_label": {
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "title": "File",
            "description": "Self management label image (PNG/JPG) or PDF to extract."
          }
        },
        "type": "object",
        "required": [
          "file"
        ],
        "title": "Body_self_management_label"
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "type": "array",
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "type": "object",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError"
      }
    },
    "securitySchemes": {
      "OAuth2PasswordBearer": {
        "type": "oauth2",
        "flows": {
          "password": {
            "scopes": {

            },
            "tokenUrl": "token"
          }
        }
      }
    }
  }
}